### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by Hunter-Github** [dhilipsiva/webapp-checklist#1]
MIT license won't do. Stack Exchange content is released under [Creative Commons Attribution-ShareAlike 3.0 Unported](https://creativecommons.org/licenses/by-sa/3.0/). Please fix ASAP. Besides, the content isn't yours.

**Comment by dhilipsiva** [comment]
@Hunter-Github Hey, thanks for letting me know. Will fix this shortly. And didn't pretend that the content was mine. Because I explicitly attributed to the source and the contributors in the [disclaimer](https://github.com/dhilipsiva/webapp-checklist#disclaimer) part of the README.md. I guess you didn't notice that.

**Comment by dhilipsiva** [comment]
@Hunter-Github If this looks good to you, I will close this Issue: https://github.com/dhilipsiva/webapp-checklist/commit/29797dfe41affc4d417d5cbf97a2410c04479b15

**Comment by Hunter-Github** [comment]
Sorry, didn't notice that. Thanks for the heads-up, can close now.

**Comment by dhilipsiva** [comment]
@Hunter-Github :smile:
